---
- ansible.builtin.include_tasks: ansible.yml
- ansible.builtin.include_tasks: usb_mount.yml
- ansible.builtin.include_tasks: samba_install.yml
- ansible.builtin.include_tasks: samba_user.yml
- ansible.builtin.include_tasks: samba_config.yml
