---
- name: "{{ nas_mount }} マウントポイントを作成する"
  ansible.builtin.file:
    path: "{{ nas_mount }}"
    state: directory
    mode: "0755"

- name: "{{ usb_device }} を {{ nas_mount }} にマウントして fstab に登録する"
  ansible.builtin.mount:
    path: "{{ nas_mount }}"
    src: "{{ usb_device }}"
    fstype: exfat
    opts: defaults,nofail,umask=000
    state: mounted
    dump: "0"
    passno: "0"
