[global]
   workgroup = WORKGROUP
   server string = Samba Server
   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file
   server role = standalone server
   map to guest = bad user
   server min protocol = SMB2
   server max protocol = SMB3

[{{ share_name }}]
   path = {{ nas_mount }}
   browseable = yes
   writable = yes

   valid users = {{ samba_user }}
   force user = {{ local_user }}
   force group = {{ local_user }}

   create mask = 0664
   directory mask = 0775
