[client]
; Client Raspberry Pis
raspi01 ansible_host=raspi01.local static_ip=192.168.0.11
raspi02 ansible_host=raspi02.local static_ip=192.168.0.12

[nas]
raspi-nas ansible_host=raspi-nas.local static_ip=192.168.0.10
