[client]
; mitaka-client ansible_host=192.168.50.17
; mitaka-client ansible_host=192.168.50.18
mitaka-client ansible_host=192.168.50.19
; mitaka-client ansible_host=192.168.50.20

[mitaka]
mitaka-client

[nas]
192.168.50.10
