[client]
raspi01 ansible_host=raspi01.local
raspi02 ansible_host=raspi02.local
raspi03 ansible_host=raspi03.local
raspi04 ansible_host=raspi04.local
raspi05 ansible_host=raspi05.local
raspi06 ansible_host=raspi06.local
raspi10 ansible_host=raspi10.local

[mitaka]
raspi01
raspi02
raspi03
raspi04
raspi05
raspi06
raspi10

[nas]
192.168.50.10
; raspi-nas ansible_host=raspi-nas.local
