[client]
; Client Raspberry Pis
; 192.168.50.11
raspi01 ansible_host=raspi01.local
; 192.168.50.12
raspi02 ansible_host=raspi02.local
; 192.168.50.13
raspi03 ansible_host=raspi03.local
; 192.168.50.14
raspi04 ansible_host=raspi04.local
; 192.168.50.15
raspi05 ansible_host=raspi05.local
; 192.168.50.16
raspi06 ansible_host=raspi06.local
; 192.168.50.20
raspi10 ansible_host=raspi10.local

[mitaka]
raspi01
raspi02
raspi03
raspi04
raspi05
raspi06
raspi10

[mitaka:vars]
extra_shortcuts=[{"url": "https://docs.google.com/spreadsheets/d/1SecD6I5mxIIdpG81uJt4ZcUy93bSKtP_m4LU4bPDj78/edit?gid=93076904", "label": "座席表"}]

[nas]
192.168.50.10
; raspi-nas ansible_host=raspi-nas.local
