[client]
; Client Raspberry Pis
raspi01 ansible_host=raspi01.local static_ip=192.168.0.196
raspi02 ansible_host=raspi02.local static_ip=192.168.0.133
raspi03 ansible_host=raspi03.local static_ip=192.168.0.128
raspi04 ansible_host=raspi04.local static_ip=192.168.0.133

[nas]
raspi-nas ansible_host=raspi-nas.local static_ip=192.168.0.128