[client]
; Client Raspberry Pis
; 192.168.0.11
raspi01 ansible_host=raspi01.local
; 192.168.0.12
raspi02 ansible_host=raspi02.local
; 192.168.0.13
raspi03 ansible_host=raspi03.local
; 192.168.0.14
raspi04 ansible_host=raspi04.local
; 192.168.0.15
raspi05 ansible_host=raspi05.local

[shinagawa]
raspi01
raspi02
raspi03
raspi04
raspi05

[shinagawa:vars]
extra_shortcuts=[{"url": "https://docs.google.com/spreadsheets/d/1M-tg2FF04A0b2sRSOtZKuy1IN5thuQFrXBAbssMLL1w/edit?gid=1809174813", "label": "座席表"}]

[nas]
192.168.0.79
