[client]
; Client Raspberry Pis
raspi01 ansible_host=raspi01.local static_ip=192.168.0.11
raspi02 ansible_host=raspi02.local static_ip=192.168.0.12
raspi03 ansible_host=raspi03.local static_ip=192.168.0.13
raspi04 ansible_host=raspi04.local static_ip=192.168.0.14
raspi05 ansible_host=raspi05.local static_ip=192.168.0.15
raspi06 ansible_host=raspi06.local static_ip=192.168.0.48

[nas]
raspi-nas ansible_host=raspi-nas.local static_ip=192.168.0.79
