[client]
; Client Raspberry Pis
; 192.168.0.11
raspi01 ansible_host=raspi01.local

[takadanobaba]
raspi01

[takadanobaba:vars]
extra_shortcuts=[{"url": "https://docs.google.com/spreadsheets/d/1ITKRhi-BYjHgpEWjjM22DY8SNNotAkpKeJLVJWUxbQg/edit?gid=1511268071", "label": "座席表"}]

[nas]
192.168.x.x
