---
- name: マウントディレクトリ作成
  ansible.builtin.file:
    path: "{{ mount_point }}"
    state: directory
    mode: "0755"

- name: cifs-utils インストール
  ansible.builtin.apt:
    name: cifs-utils
    state: present

- name: fstab に NAS マウント設定追加
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "//{{ groups['nas'][0] }}/{{ nas_share }}   {{ mount_point }}   cifs   username={{ nas_user }},password={{ nas_pass }},iocharset=utf8,uid=1000,gid=1000,nofail,_netdev   0   0"
    create: true
