---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: credential.txt が配置されていることを確認する
      ansible.builtin.stat:
        path: /home/swimmy/Documents/credential.txt
      register: document_credential_file
      failed_when: not document_credential_file.stat.exists

    - name: credential.txt の権限が0600であることを確認する
      ansible.builtin.assert:
        that:
          - document_credential_file.stat.mode == "0600"
