---
- name: Python環境インストール
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: true

- name: ライブラリ・モジュールをインストールする
  ansible.builtin.pip:
    name:
      - pygame
      - flask
      - keyboard
    state: present
    extra_args: --break-system-packages
